env:
  MY_SECRET: ${{ secrets.OPENAI_API_KEY }}

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Print secret
        run: echo "Secret is $OPENAI_API_KEY"